all: pr1 pr2 pr3a pr3b pr3c pr4            

clean:
	rm -f pr1 pr2 pr3a pr3b pr3c pr4        

pr1: pr1.c
	gcc -o pr1 pr1.c -Wall

pr2: pr2.c
	gcc -o pr2 pr2.c -Wall

pr3a: pr3a.c
	gcc -o pr3a pr3a.c -Wall

pr3b: pr3b.c
	gcc -o pr3b pr3b.c -Wall

pr3c: pr3c.c
	gcc -o pr3c pr3c.c -Wall

pr4: pr4.c
	gcc -o pr4 pr4.c -Wall

